- project:
    templates:
      - openstack-cover-jobs
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - lib-forward-testing-python3
      - release-notes-jobs-python3
      - openstackclient-plugin-jobs
    check:
      jobs:
        - neutronclient-functional
    gate:
      jobs:
        - neutronclient-functional
    experimental:
      jobs:
        - neutronclient-grenade-neutron-lib:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$

- job:
    name: neutronclient-functional
    parent: devstack-tox-functional
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
    required-projects:
      - openstack/python-neutronclient
      - openstack/neutron
      - openstack/neutron-vpnaas
    vars:
      tox_envlist: functional
      devstack_services:
        # NOTE: neutronclient.tests.functional.base.ClientTestBase does not
        # support HTTPS endpoints now, so tls-proxy needs to be disabled.
        tls-proxy: false
        # Disable OVN services
        br-ex-tcpdump: false
        br-int-flows: false
        ovn-controller: false
        ovn-northd: false
        ovs-vswitchd: false
        ovsdb-server: false
        q-ovn-metadata-agent: false
        # Neutron services
        q-agt: true
        q-dhcp: true
        q-l3: true
        q-meta: true
        neutron-network-segment-range: true
        neutron-segments: true
        q-metering: true
        q-qos: true
        neutron-tag-ports-during-bulk-creation: true
        neutron-conntrack-helper: true
      devstack_localrc:
        USE_PYTHON3: true
        LIBS_FROM_GIT: python-neutronclient
        Q_AGENT: openvswitch
        Q_ML2_TENANT_NETWORK_TYPE: vxlan
        Q_ML2_PLUGIN_MECHANISM_DRIVERS: openvswitch
      devstack_plugins:
        neutron: https://opendev.org/openstack/neutron
        neutron-vpnaas: https://opendev.org/openstack/neutron-vpnaas

- job:
    name: neutronclient-grenade-neutron-lib
    parent: grenade
    description: |
      neutron-lib grenade job.
      The version of this job on the current branch is py3 based,
      while any branch before ussuri needs to use the py2 version,
      which is defined in openstack-zuul-jobs with the old name
      (legacy-grenade-dsvm-neutron-libs).
      Users of this job needs to pay attention of the version used.
      Former names for this job were:
        * legacy-grenade-dsvm-neutron-libs
        * neutron-lib-grenade-dsvm
    required-projects:
      - openstack/keystoneauth
      - openstack/neutron
      - openstack/neutron-lib
      - openstack/os-client-config
      - openstack/python-cinderclient
      - openstack/python-glanceclient
      - openstack/python-ironicclient
      - openstack/python-keystoneclient
      - openstack/python-neutronclient
      - openstack/python-novaclient
